apiVersion: v1
kind: Service
metadata:
  name: rollouts-demo
  labels:
    app: rollouts-demo
spec:
  type: LoadBalancer
  selector:
    app: rollouts-demo
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: rollouts-demo-canary
  labels:
    app: rollouts-demo
spec:
  selector:
    app: rollouts-demo
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
